### ISSUE TITLE
Add PrefersNonDefaultGPU=true to the desktop file

### ISSUE THREAD

**Issue by soredake** [flathub/org.citra_emu.citra#1]
To start citra on powerful gpu by default.

https://github.com/pop-os/steam/pull/3
https://github.com/flathub/com.valvesoftware.Steam/issues/559
https://gitlab.freedesktop.org/xdg/xdg-specs/-/merge_requests/13

**Comment by liushuyu** [comment]
Thank you very much for the report! I will open a new Pull Request on the upstream to add this,

**Comment by liushuyu** [comment]
Sorry for the wait, the fix is in progress: https://github.com/citra-emu/citra/pull/5772.
