### ISSUE TITLE
Verify ownership on beta.flathub.org

### ISSUE THREAD

**Issue by barthalion** [flathub/org.citra_emu.citra#389]
Hi @liushuyu,

We're preparing for the launch of beta.flathub.org, and would like to see Citra verified as maintained by its developers. Currently, I've marked it as such manually, but it would be preferred to use one of the verification features. This can be initiated by logging it at https://beta.flathub.org/login with a GitHub account, pressing "Developer Settings" and following the instructions there.

Please let me know when it's done, so I can remove the manual verification flag.

**Comment by liushuyu** [comment]
Hi there,

As much as I would like to proceed with the verification process, I am having issues with your system.

I can't un-verify the current to begin the re-verification process. Can you help me to understand how should I do that?

**Comment by barthalion** [comment]
This has been sorted out on Matrix. Thanks!
