### ISSUE TITLE
citra flatpak crashes immediately unless run from the command line

### ISSUE THREAD

**Issue by powerpuffboysz** [flathub/org.citra_emu.citra#469]
if i run this "flatpak run org.citra_emu.citra" the flatpak works fine, but if i try to run it from the kde menu or as a desktop shortcut it will imediately crash. using manjaro.

**Comment by powerpuffboysz** [comment]
citra log spits out this:


[   0.002336] Frontend <Critical> citra/citra.cpp:main:338: Failed to load ROM: No ROM specified

**Comment by Steveice10** [comment]
Fixed by https://github.com/flathub/org.citra_emu.citra/pull/471
