### ISSUE TITLE
Citra crashes on launch

### ISSUE THREAD

**Issue by deadmeu** [flathub/org.citra_emu.citra#496]
Initially raised upstream https://github.com/citra-emu/citra/issues/6847 Citra is crashing at launch with this error `/usr/include/c++/12.2.0/bits/unique_ptr.h:445: typename std::add_lvalue_reference<_Tp>::type std::unique_ptr<_Tp, _Dp>::operator*() const [with _Tp = Memory::MemorySystem; _Dp = std::default_delete<Memory::MemorySystem>; typename std::add_lvalue_reference<_Tp>::type = Memory::MemorySystem&]: Assertion 'get() != pointer()' failed.`

It looks like there's a good chance it's Flatpak specific so I'm raising it as an issue here.

**Comment by Steveice10** [comment]
This particular issue is resolved upstream and can be closed.
